# Generated by Django 4.2.3 on 2023-07-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemoranchees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemoran',
            options={'ordering': ['-id']},
        ),
    ]
