# Generated by Django 4.2.3 on 2023-07-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemoranchees', '0003_pemoran_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemoran',
            name='user',
        ),
    ]
