# Generated by Django 4.2.3 on 2023-07-29 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pemoranchees', '0005_pemoran_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemoran',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PemoranLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pemoran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pemoranchees.pemoran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pemoran',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='pemoran_user', through='pemoranchees.PemoranLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
