# Generated by Django 4.2.3 on 2023-07-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemoranchees', '0006_pemoran_created_at_pemoranlike_pemoran_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemoran',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pemoranchees.pemoran'),
        ),
    ]
